version: '2'

services:
  varnish:
    container_name: varnish-varnish
    image: "tstrohmeier/gquintard-varnish-docker"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
     - "1080:80"
    environment:
     - SINGLE=varnish
     - VARNISH_OPTS=-n /var/lib/varnish -T :6082
    volumes:
     - ./vsl:/var/lib/varnish
  hitch:
    container_name: varnish-hitch
    image: "tstrohmeier/gquintard-varnish-docker"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
     - "1443:443"
    environment:
     - SINGLE=hitch
     - HITCH_OPTS=
  agent:
    container_name: varnish-agent
    image: "tstrohmeier/gquintard-varnish-docker"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
     - "1085:6085"
    environment:
     - SINGLE=agent
     - AGENT_OPTS=-n /var/lib/varnish -T varnish:6082
     - STAT_OPTS=-n /var/lib/varnish
    volumes:
     - ./vsl:/var/lib/varnish


volumes:
  workdir:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
